### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/RetroArch#2]
https://github.com/libretro/RetroArch/compare/master...RobLoach:favorites?expand=1&title=Add%20Favorites&body=Add%20the%20ability%20to%20save%20favorites

## TODO

- [ ] Callback to add to favorites
- [ ] Add to fav icon
- [ ] Setting to hide the tab

@kivutar already did the special tab.
